### PR TITLE
Ryan's project

### PR DESCRIPTION
**Pull request by rabernat**
I started my project proposal, but then I realized I had to leave. Will finish later.

### CODE REVIEW

**Comment by rabernat** [comment]
Ok, I think this is now complete.

**Comment by tjcrone** [comment]
This is great! Although I'm pretty sure that the description will look best on the site if it is all on one line.

**Comment by tjcrone** [comment]
Or will the line breaks not show up?

**Comment by tjcrone** [comment]
Looks like the line breaks will not appear as breaks when rendered. I'm merging.

**Pull request merged**
